<!DOCTYPE raiz
[
<!ELEMENT raiz(a|b)*>
<!ELEMENT a(#PCDATA)>
<!ELEMENT b(#PCDATA)>
]>
<raiz>
<b></b>
<a></a>
<a></a>
<b></b>
<b></b>
</raiz>