<!DOCTYPE CASA
[
<!ELEMENT CASA (CUARTO, BAÑO)>
<!ELEMENT CUARTO (CAMA)>
<!ELEMENT CAMA (#PCDATA)>
<!ELEMENT BAÑO (#PCDATA, TAZA)>
<!ELEMENT TAZA (#PCDATA)>
]>

<CASA>
	<CUARTO>
		<CAMA>EL EDREDON ES DEL REAL MADRID</CAMA>
	</CUARTO>
	<BAÑO>
		DENTRO DEL BAÑO TAMBIÉN ESTÁ LA REGADERA
		<TAZA></TAZA>
	</BAÑO>

</CASA>