<!DOCTYPE RAIZ[
<!ELEMENT RAIZ (#PCDATA, DATOS , CEL,GENERO)>
<!ELEMENT DATOS (NOMBRE+, APELLIDO+)>
<!ELEMENT NOMBRE (#PCDATA)>
<!ELEMENT APELLIDO (#PCDATA)>
<!ELEMENT CEL (#PCDATA)>
<!ELEMENT GENERO ANY>
]>


<RAIZ>
	ANOTE SUS DATOS CORRESPONDIENTES
	<DATOS>
		<NOMBRE>VALERY</NOMBRE>
		<APELLIDO>GARIBAY</APELLIDO>
	</DATOS>
	<CEL>5556211455</CEL>
	<GENERO />
</RAIZ>