<!DOCTYPE RAIZ
[
<!ELEMENT RAIZ (#PCDATA, DATOS, SEPARATED, CELULAR, GENERO)>
<!ELEMENT DATOS (#PCDATA, NOMBRE+,APELLIDO+)>
<!ELEMENT NOMBRE (#PCDATA)>
<!ELEMENT APELLIDO (#PCDATA)>
<!ELEMENT SEPARATED EMPTY>
<!ELEMENT CELULAR (#PCDATA)>
<!ELEMENT GENERO EMPTY>
]>




<RAIZ>
	BASE DE DATOS DE MUJERES
	<DATOS>
		<NOMBRE>VIRIDIANA</NOMBRE>
		<APELLIDO>HUERTA</APELLIDO>
	</DATOS>
	<SEPARATED />
	<CELULAR></CELULAR>
	<GENERO />
</RAIZ>