<!DOCTYPE AUTOMOVIL
[
<!ELEMENT AUTOMOVIL (#PCDATA, CAJUELA?, ASIENTO+, ESPEJO+, LLANTA+)>
<!ELEMENT CAJUELA (#PCDATA, LLANTA+)>
<!ELEMENT LLANTA (#PCDATA)>
<!ELEMENT ASIENTO (#PCDATA)>
<!ELEMENT ESPEJO (#PCDATA)>
<!ELEMENT LLANTA (#PCDATA)>
]>


<AUTOMOVIL>
	<CAJUELA>
		SE GUARDAN COSAS EXTRAS
		<LLANTA>
			PUEDE ESTAR UNA O M√ÅS LLANTAS DE REPUESTO
		</LLANTA>
	</CAJUELA>
	<ASIENTO>
		AQUI ES PARA QUE UNA  O MAS PERSONAS SE SIENTEN
	</ASIENTO>
	<ESPEJO></ESPEJO>
	<LLANTA></LLANTA>
</AUTOMOVIL>